version: "3.4"

services:
  mysqldb:
   container_name: mysqldb
   image: mysql:latest
   restart: unless-stopped
   ports:
    - 3306:3306
   environment:
    MYSQL_DATABASE: achatdb
    MYSQL_ROOT_PASSWORD: pass
   volumes:
     - mysqldb:/var/lib/mysql:rw 

  spring_app:
   image: mahdiben/app:latest
   container_name: achat
   restart: on-failure
   ports:
    - 8089:8089
   depends_on:
    - mysqldb
   
volumes:
   mysqldb: {} 