version: "3.4"

services:
  mysql-containerik:
    container_name: mysql-containerik
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    restart: always
    volumes:
      - mysql-containerik:/var/lib/mysql
    image: 'mysql:latest'
  dockerfile_springik:
    depends_on:
      - mysql-containerik
    container_name: dockerfile_springik
    ports:
      - '8089:8089'
    image: ikbelfridhi/dockerfile_spring:2.2.4

volumes:
  mysql-containerik: { }