version: "2"

services:
  mysqldb:
   container_name: mysqldb
   image: mysql:8
   restart: unless-stopped
   ports:
    - 3306:3306
   environment:
    MYSQL_DATABASE: achatdb
    MYSQL_ROOT_PASSWORD: pass
   volumes:
     - /home/mysql/data:/var/lib/mysql --user 1000

  spring_app:
   image: achatapp
   container_name: achatprojet
   restart: on-failure
   ports:
    - 8089:8089
   depends_on:
    - mysqldb
